FROM python:3.9

# Set working directory
WORKDIR /root/app

# Copy application files
COPY . .

# Install dependencies
RUN pip install -r requirements.txt

# Expose the correct port
EXPOSE 8086

# Run the application
CMD ["python", "app.py"]

